require("configs.alpha")
require("configs.cmp")
require("configs.color")
require("configs.fzf")
require("configs.mason")
require("configs.oil")
require("configs.rename")
require("configs.treesitter")
